SELECT B.CATEGORY, SUM(S.SALES)
FROM BOOK AS B JOIN BOOK_SALES AS S
ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = DATE_FORMAT(now(), '2022-01')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC